version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:11"
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: "yarn install"
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'

      - run:
        name: Install Firebase
        command: npm install --save-dev firebase-tools

      - run:
        name: "Build Project"
        command: "yarn build"

      - run:
        name: "Deploy to Firebase Hosting"
        command: "./node_modules/.bin/firebase deploy --token=$FIRE_BASE_TOKEN"
